tools:
  nodejs: 9.5.0
  npm: 5.6.0

flows:
  default:
    - node -v
    - npm -v
    - ls
    - npm install
    - node_modules/babel-cli/bin/babel.js ./src/server -d build/server
    - node_modules/webpack/bin/webpack.js --config ./webpack.dev.config.js
    - ls build/
    - ls build/server/
